version: '3.8'

services:
  wallet-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=wallet_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - SERVER_PORT=8080
    depends_on:
      - postgres
    networks:
      - wallet-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=wallet_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wallet-network

volumes:
  postgres_data:

networks:
  wallet-network:
